### PR TITLE
improving readme: adding link to contribution.md

### PR DESCRIPTION
**Pull request by LeonardoFurtado**
Add link to your contribution guide in README to help new users find it easily. It is a good practice

### CODE REVIEW

**Comment by LeonardoFurtado** [comment]
it fail, I will fix.

**Comment by twcook** [comment]
It passed CI

**Comment by twcook** [comment]
Ah, I see. it's not a link. :-)

**Comment by LeonardoFurtado** [comment]
> It passed CI

See readme.

**Comment by LeonardoFurtado** [comment]
yep haha

**Pull request merged**
